git add build.gradle.kts
git add shardscript-semantics/src
git add shardscript-semantics/build.gradle.kts
git add shardscript-grammar/src/main/antlr/ShardScriptLexer.g4
git add shardscript-grammar/src/main/antlr/ShardScriptParser.g4
git add shardscript-grammar/build.gradle.kts
git add shardscript-composition/src
git add shardscript-composition/build.gradle.kts
git add shardscript-eval/src
git add shardscript-eval/build.gradle.kts
git add shardscript-acceptance/src
git add shardscript-acceptance/build.gradle.kts
